[tool.poetry]
name = "Adjust SDK documentation"
version = "0.1.0"
description = ""
authors = ["Adjust GmbH"]

[tool.poetry.dependencies]
python = "^3.10"
sphinx = "==5.3.0"
sphinx-rtd-theme = "==1.1.1"
myst-parser = "==0.18.1"
sphinx-multiversion = "0.2.4"
sphinx-intl = "2.0.1"
sphinx_design = "==0.3.0"
sphinxcontrib-mermaid = "0.7.1"
sphinxcontrib-images = "^0.9.4"
sphinx-copybutton = "^0.5.1"

[tool.poetry.group.dev.dependencies]
livereload = "^2.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
